# Generated by Django 4.0.3 on 2022-04-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_attendancerange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceclass',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('8:10 - 9:10', '8:10 - 9:10'), ('9:10 - 10:10', '9:10 - 10:10'), ('10:10 - 10:25', '10:10 - 10:25'), ('10:25 - 11:25', '10:25 - 11:25'), ('11:25 - 12:25', '11:25 - 12:25'), ('12:25 - 12:45', '12:25 - 12:45'), ('12:45 - 01:45', '12:45 - 01:45'), ('01:45 - 02:45', '01:45 - 02:45')], default='11:00 - 11:50', max_length=50),
        ),
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(choices=[('Internals 1', 'Internals 1'), ('Internals 2', 'Internals 2'), ('Viva', 'Viva'), ('Practicals', 'Practicals'), ('Termwork', 'Termwork'), ('End Semester', 'End Semester')], default='Internals 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='name',
            field=models.CharField(choices=[('Internals 1', 'Internals 1'), ('Internals 2', 'Internals 2'), ('Viva', 'Viva'), ('Practicals', 'Practicals'), ('Termwork', 'Termwork'), ('End Semester', 'End Semester')], default='Internals 1', max_length=50),
        ),
    ]
