# Generated by Django 4.0.3 on 2022-04-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_alter_attendanceclass_options_alter_assigntime_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('8:10 - 9:10', '8:10 - 9:10'), ('9:10 - 10:10', '9:10 - 10:10'), ('10:25 - 11:25', '10:25 - 11:25'), ('11:25 - 12:25', '11:25 - 12:25'), ('12:45 - 01:45', '12:45 - 01:45'), ('01:45 - 02:45', '01:45 - 02:45')], default='11:00 - 11:50', max_length=50),
        ),
    ]
